# Robot name goes here
my_navigation_impl: # change the name
  # default controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controller 1
  FR_wheel_controller: # change the name
    type: velocity_controllers/JointVelocityController # Type of controller. 
    joint: FR_joint # Name of the joint.  
    pid : {p: 20.0 , i: 0.0 , d: 2.0}  # Enter your pid values eg. {p: 100.0 , i: 0.0 , d: 0.0} 

  # Controller 2
  FL_wheel_controller: # change the name
    type: velocity_controllers/JointVelocityController # Type of controller. 
    joint: FL_joint # Name of the joint.  
    pid : {p: 20.0 , i: 0.0 , d: 2.0} 

  # Controller 3
  BR_wheel_controller: # change the name
    type: velocity_controllers/JointVelocityController # Type of controller. 
    joint: BR_joint # Name of the joint.  
    pid : {p: 20.0 , i: 0.0 , d: 2.0}   

  # Controller 4
  BL_wheel_controller: # change the name
    type: velocity_controllers/JointVelocityController # Type of controller. 
    joint: BL_joint # Name of the joint.  
    pid : {p: 20.0 , i: 0.0 , d: 2.0}   
  

